Apply changes after refactoring in uhdm-integration repo
litex-hub/litex-conda-eda pull request #74
Opened 2021-01-27 18:10 UTC by wtatarski

2021-01-29 16:28 UTC, tgorochowik commented
This needs to go in first, right: https://github.com/alainmarcel/uhdm-integration/pull/163 ?

2021-01-29 16:42 UTC, wtatarski commented
> This needs to go in first, right: [alainmarcel/uhdm-integration#163](https://github.com/alainmarcel/uhdm-integration/pull/163) ?

Actually this should be merged as the last one -> https://github.com/alainmarcel/uhdm-integration/issues/177

2021-01-29 19:41 UTC, ajelinski requested changes
I can see that the CI jobs succeeded with each of the recipes containing a test command so it seems that the build script changes work.

The version lines need to be restored since changing them is pointless.

Otherwise, LGTM.

2021-01-29 19:41 UTC, ajelinski commented on sim/verilator-uhdm/meta.yaml
> +{% set version = GIT_DESCRIBE_HASH %}
Don't change this line. It doesn't influence the final version of the package as it is set by conda-build-prepare in CI.

2021-01-29 19:41 UTC, ajelinski commented on syn/yosys-uhdm/meta.yaml
> +{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('yosys-', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
Don't change this line. It doesn't influence the final version of the package as it is set by conda-build-prepare in CI.

2021-02-01 13:35 UTC, wtatarski commented
@ajelinski  
I resolved your issues, but there is a fault in `prjtrellis-windows` and `master-package`.  I did not change anything in those packages. So has it happened before?

2021-02-01 16:55 UTC, ajelinski commented
I can see `prjtrellis-windows` failed because of QT servers again (there was a problem with their servers lately that lasted a couple of days):
```
   -- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip... Failed. Status: 28;"Timeout was reached"
```
Now this file is available so after rerunning tests the job has passed.

The PR changes LGTM now and can be merged when the related repositories got their PRs merged. I'll leave my review as "Changes requested" to not forget to change the `git_rev` before merging.

2021-02-01 16:59 UTC, ajelinski requested changes
LGTM. The review is still "Request changes" only to remember about changing branches in `git_rev`.

2021-02-01 16:59 UTC, ajelinski commented on sim/verilator-uhdm/meta.yaml
> +  git_rev: add-ci
Change it before merging.

2021-02-01 16:59 UTC, ajelinski commented on syn/yosys-uhdm/meta.yaml
> +  git_rev: add-ci
Change it before merging.

2021-02-01 17:37 UTC, wtatarski commented on sim/verilator-uhdm/meta.yaml
> +  git_rev: add-ci
Changed to `uhdm-verilator`

2021-02-01 17:37 UTC, wtatarski commented on syn/yosys-uhdm/meta.yaml
> +  git_rev: add-ci
Changed to `uhdm-yosys`

2021-02-01 17:38 UTC, wtatarski commented
Changes in yosys and verilator was merged to base branches. Should be OK now.

2021-02-02 09:22 UTC, ajelinski commented
I was wondering about the source repository changes but I can see these are the ones originally used before changes in `uhdm-integration`: https://github.com/alainmarcel/uhdm-integration/pull/163/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584L1

2021-02-02 09:22 UTC, ajelinski approved these changes

2021-02-02 09:22 UTC, merged